// <auto-generated />
using System;
using KhoaCNTT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhoaCNTT.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327185623_RemoveSizeFromNewsResource")]
    partial class RemoveSizeFromNewsResource
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins", t =>
                        {
                            t.HasCheckConstraint("CK_Admin_Level", "[Level] >= 1");
                        });
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.FileEntities.FileApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileApprovalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("FileRequestId");

                    b.ToTable("FileApproval", (string)null);
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.FileEntities.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CurrentResourceId")
                        .HasColumnType("int");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CurrentResourceId");

                    b.HasIndex("SubjectCode");

                    b.ToTable("FileEntity", (string)null);
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.FileEntities.FileRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileRequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<int>("NewResourceId")
                        .HasColumnType("int");

                    b.Property<int?>("OldResourceId")
                        .HasColumnType("int");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int?>("TargetFileId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NewResourceId");

                    b.HasIndex("OldResourceId");

                    b.HasIndex("SubjectCode");

                    b.HasIndex("TargetFileId");

                    b.ToTable("FileRequest", (string)null);
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.FileEntities.FileResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FileResourceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("char(255)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("FileResource", (string)null);
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.LecturerSubject", b =>
                {
                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("LecturerId", "SubjectCode");

                    b.HasIndex("SubjectCode");

                    b.ToTable("LecturerSubjects");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CommentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("MSV")
                        .IsRequired()
                        .HasColumnType("CHAR(10)");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CurrentResourceId")
                        .HasColumnType("int");

                    b.Property<string>("NewsType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CurrentResourceId");

                    b.ToTable("News", (string)null);
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.NewsApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewsApprovalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NewsRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("NewsRequestId");

                    b.ToTable("NewsApproval", (string)null);
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.NewsRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewsRequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<int>("NewResourceId")
                        .HasColumnType("int");

                    b.Property<string>("NewsType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("OldResourceId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TargetNewsId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NewResourceId");

                    b.HasIndex("OldResourceId");

                    b.HasIndex("TargetNewsId");

                    b.ToTable("NewsRequest", (string)null);
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.NewsResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewsResourceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("NewsResource", (string)null);
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.Subject", b =>
                {
                    b.Property<string>("SubjectCode")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectCode");

                    b.HasIndex("SubjectCode")
                        .IsUnique();

                    b.ToTable("Subjects", t =>
                        {
                            t.HasCheckConstraint("CK_Subject_Credits", "[Credits] > 0");
                        });
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.FileEntities.FileApproval", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhoaCNTT.Domain.Entities.FileEntities.FileRequest", "FileRequest")
                        .WithMany()
                        .HasForeignKey("FileRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("FileRequest");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.FileEntities.FileEntity", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhoaCNTT.Domain.Entities.FileEntities.FileResource", "CurrentResource")
                        .WithMany()
                        .HasForeignKey("CurrentResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhoaCNTT.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectCode");

                    b.Navigation("Admin");

                    b.Navigation("CurrentResource");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.FileEntities.FileRequest", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.FileEntities.FileResource", "NewResource")
                        .WithMany()
                        .HasForeignKey("NewResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhoaCNTT.Domain.Entities.FileEntities.FileResource", "OldResource")
                        .WithMany()
                        .HasForeignKey("OldResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KhoaCNTT.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KhoaCNTT.Domain.Entities.FileEntities.FileEntity", "TargetFile")
                        .WithMany()
                        .HasForeignKey("TargetFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NewResource");

                    b.Navigation("OldResource");

                    b.Navigation("Subject");

                    b.Navigation("TargetFile");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.FileEntities.FileResource", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.LecturerSubject", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.Lecturer", "Lecturer")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaCNTT.Domain.Entities.Subject", "Subject")
                        .WithMany("LecturerSubjects")
                        .HasForeignKey("SubjectCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.Comment", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.NewsEntities.News", "News")
                        .WithMany("Comments")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.News", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhoaCNTT.Domain.Entities.NewsEntities.NewsResource", "CurrentResource")
                        .WithMany()
                        .HasForeignKey("CurrentResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("CurrentResource");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.NewsApproval", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhoaCNTT.Domain.Entities.NewsEntities.NewsRequest", "NewsRequest")
                        .WithMany()
                        .HasForeignKey("NewsRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("NewsRequest");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.NewsRequest", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.NewsEntities.NewsResource", "NewResource")
                        .WithMany()
                        .HasForeignKey("NewResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KhoaCNTT.Domain.Entities.NewsEntities.NewsResource", "OldResource")
                        .WithMany()
                        .HasForeignKey("OldResourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KhoaCNTT.Domain.Entities.NewsEntities.News", "TargetNews")
                        .WithMany()
                        .HasForeignKey("TargetNewsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NewResource");

                    b.Navigation("OldResource");

                    b.Navigation("TargetNews");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.NewsResource", b =>
                {
                    b.HasOne("KhoaCNTT.Domain.Entities.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.Lecturer", b =>
                {
                    b.Navigation("LecturerSubjects");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.NewsEntities.News", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("KhoaCNTT.Domain.Entities.Subject", b =>
                {
                    b.Navigation("LecturerSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
